export const SET_MOVIESLIST = "SET_MOVIESLIST";
export const SET_MOVIEDETAIL = "SET_MOVIEDETAIL";
export const SET_MOVIETRAILLER = "SET_MOVIETRAILLER";
export const SET_MOVIETRAILLERMODAL = "SET_MOVIETRAILLERMODAL";
